import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { ThemeContextProvider } from "@/contexts/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import Footer from "@/components/footer/Footer";
import ThemeSwitcher from "@/components/themeSwitcher/ThemeSwitcher";
import { PathProvider } from "@/contexts/pathContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProvider>
            <PathProvider>
              <Navbar />
              {children}
              <ThemeSwitcher />
              <Footer />
            </PathProvider>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
